### PR TITLE
Update German translation

### PR DESCRIPTION
**Pull request by mvdberge**
Just updated and improved the German translation. Should also be done on other project parts...

### CODE REVIEW

**Review by pabloelcolombiano — APPROVED** [review]
Thank you for the contribution, this looks good.

**Comment by pabloelcolombiano** [comment]
@mvdberge thank you for your contribution, this is very appreciated!

Note that we use a dedicated tool, Crowdin, to manage the translations. You will find more information here: https://help.passbolt.com/contribute/translation

Looking forward to your contributions!

**Comment by mvdberge** [comment]
OK, sorry for my ignorance - will use Crowdin next time. :innocent:
Can these changes be merged anyway? Or must I recreate them in Crowdin manually?

**Comment by cedricalfonsi** [comment]
@mvdberge Your commit was merged with v4.8.0.
Thank you for your contribution 🙏

**Pull request closed without merging**
